services:
  database:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-api
    restart: always
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://database:27017/ecommerce
      - JWT_SECRET=your_jwt_secret_here
    depends_on:
      - database
    volumes:
      - ./backend:/app
      - /app/node_modules

volumes:
  mongo-data:
